language: node_js
node_js:
  - "0.12"
  - 6
  - 5
branches:
  only:
    - master
before_script:
  - npm install mocha
  - npm install grunt-cli -g
  - grunt config manifest dist-files
after_success:
  - grunt all
